spring:
  application:
    name: techintcap
  datasource:
    url: jdbc:h2:mem:techintcap;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

techintcap:
  discount:
    category:
      Electronics: 0.15
      Home & Kitchen: 0.25
    sku:
      five:
        endsWith: 5
        discount: 0.30
  pagination:
    defaultSize: 10

